### PR TITLE
PR2 Fork net/mail and fixes based on that

### PR DESCRIPTION
**Pull request by exander77**
Split from previous.

### CODE REVIEW

**Comment by exander77** [comment]
@jameshoulahan I move conversation here, ANTLR seems to have good support for Golang, so it should be a good way to go.

**Comment by exander77** [comment]
@jameshoulahan 
I have stitched together grammar for Anltr4 and made a parser and it works very well so far. If I disregard non US-ASCII characters in headers, it only failed for dates on these:
```
6 Oct 2016 13:48:22
Fri, 28 May 2010 10:43:37 (GMT)
Mon, 12 May 2014 21:06:45 
Thu, 11 Sep 2014 1:15:09 +0200 
Tuesday 02 March 2010 04:02:33 PM
```
And for addresses on these types:
```
<> ; empty angle-addr
Mailer <> ; empty angle-addr
Some Body @ Somewhere <somebody@somewhere.com>
Somebody :: Somewhere <somebody@somewhere.com>
Somebody, Somewhere <somebody@somewhere.com>
Somebody somebody@somewhere.com ; missing angle-addr
somebody ; missing angle-addr
<somebody somewhere> ; broken angle-addr
undisclosed-recipients: ; group without semicolon
```
The parser is directly taken from RFC 5322 and RFC 2047. It requires all the rules as they are specified in ABNF, but does not enforce some additional restriction mentioned there.

So I assume, it is not that hard to make a parser.

With a few alterations, this could be relaxed to parse almost everything.

**Comment by exander77** [comment]
@jameshoulahan Any new on pulling my changes? With this speed, I will make a parser myself. I have a complete grammar (with extensions to cover non-standard behaviour) for Antlr and I construct date and address list for the most trivial case. Have to add more parser rules for obsoletes and encodings.

**Comment by jameshoulahan** [comment]
No news from our side yet.

**Comment by exander77** [comment]
@jameshoulahan Thank's for the info.

I have run a comparison for `net/mail` (GO), forked and patched `net/mail` (GP) and my Antlr based parser (GA):

```
IN: <>
GO: [] mail: invalid string
GP: [<@>] %!s(<nil>)
GA: [<@>] %!s(<nil>)

IN: Mailer <>
GO: [] mail: invalid string
GP: ["Mailer" <@>] %!s(<nil>)
GA: ["Mailer" <@>] %!s(<nil>)

IN: Somebody Somewhere <somebody@somewhere.com.>
GO: [] mail: trailing dot in atom
GP: ["Somebody Somewhere" <somebody@somewhere.com.>] %!s(<nil>)
GA: ["Somebody Somewhere" <somebody@somewhere.com.>] %!s(<nil>)

IN: Somebody Somewhere <somebody@somewhere.com >
GO: [] mail: unclosed angle-addr
GP: ["Somebody Somewhere" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Somewhere" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody Somewhere <somebody@somewhere.com. >
GO: [] mail: trailing dot in atom
GP: ["Somebody Somewhere" <somebody@somewhere.com.>] %!s(<nil>)
GA: ["Somebody Somewhere" <somebody@somewhere.com.>] %!s(<nil>)

IN: Somebody Somewhere <somebody@somewhere.com:25>
GO: [] mail: unclosed angle-addr
GP: [] mail: unclosed angle-addr
GA: ["Somebody Somewhere" <somebody@somewhere.com:25>] %!s(<nil>)

IN: Somebody Somewhere <somebody@[10.0.0.1]>
GO: [] mail: invalid string
GP: [] mail: invalid string
GA: ["Somebody Somewhere" <somebody@[10.0.0.1]>] %!s(<nil>)

IN: somebody@somewhere <somebody@somewhere.com>
GO: [] mail: expected comma
GP: ["somebody@somewhere" <somebody@somewhere.com>] %!s(<nil>)
GA: ["somebody somewhere" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody :: Somewhere <somebody@somewhere.com>
GO: [] mail: missing word in phrase: mail: invalid string
GP: [] mail: missing word in phrase: mail: invalid string
GA: ["Somebody" <@>] %!s(<nil>)

IN: Somebody Somewhere < somebody@somewhere.com>
GO: ["Somebody Somewhere" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody Somewhere" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Somewhere" <somebody@somewhere.com>] %!s(<nil>)

IN: Some Body @ Somewhere <somebody@somewhere.com>
GO: ["Some Body @ Somewhere" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Some Body @ Somewhere" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Some Body Somewhere" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody Somewhere <somebody somewhere>
GO: [] mail: missing @ in addr-spec
GP: [] mail: missing @ in addr-spec
GA: [] mail: 1 syntax errors encountered

IN: somebody
GO: [] mail: missing '@' or angle-addr
GP: [] mail: missing '@' or angle-addr
GA: [<somebody@>] %!s(<nil>)

IN: Somebody, Somewhere <somebody@somewhere.com>
GO: ["Somebody, Somewhere" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody, Somewhere" <somebody@somewhere.com>] %!s(<nil>)
GA: [<Somebody@> "Somewhere" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody somebody@somewhere.com
GO: [] mail: no angle-addr
GP: [] mail: no angle-addr
GA: ["Somebody" <somebody@somewhere.com>] %!s(<nil>)

IN: undisclosed-recipients:
GO: [] mail: no address
GP: [] %!s(<nil>)
GA: ["undisclosed-recipients" <@>] %!s(<nil>)

IN: Somebody Alfa "Beta" <somebody@somewhere.com>
GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody Alfa Beta <somebody@somewhere.com>
GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody Alfa"Beta" <somebody@somewhere.com>
GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody Alfa "Beta"<somebody@somewhere.com>
GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody "Alfa" "Beta" <somebody@somewhere.com>
GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody "Alfa""Beta" <somebody@somewhere.com>
GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody Alfa =?utf-8?Q?Beta?= <somebody@somewhere.com>
GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody Alfa=?utf-8?Q?Beta?= <somebody@somewhere.com>
GO: ["Somebody Alfa=?utf-8?Q?Beta?=" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody Alfa=?utf-8?Q?Beta?=" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Alfa=?utf-8?Q?Beta?=" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody Alfa =?utf-8?Q?Beta?=<somebody@somewhere.com>
GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GP: [] mail: no angle-addr
GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody =?utf-8?Q?Beta?= =?utf-8?Q?Beta?= <somebody@somewhere.com>
GO: ["Somebody BetaBeta" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody BetaBeta" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody BetaBeta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody =?utf-8?Q?Beta?==?utf-8?Q?Beta?= <somebody@somewhere.com>
GO: ["Somebody =?utf-8?Q?Beta?==?utf-8?Q?Beta?=" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody BetaBeta" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody BetaBeta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody "Alfa" =?utf-8?Q?Beta?= <somebody@somewhere.com>
GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody "Alfa"=?utf-8?Q?Beta?= <somebody@somewhere.com>
GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)

IN: Somebody "Alfa" =?utf-8?Q?Beta?=<somebody@somewhere.com>
GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
GP: [] mail: no angle-addr
GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] %!s(<nil>)
```

**Comment by jameshoulahan** [comment]
Just came back to give an update, we've now begun work building a parser from the formal grammar. Will keep you posted on the outcome.

Regarding the comparison: looks good! The output of the parser is a `mail.Address` object, right?

**Comment by exander77** [comment]
@jameshoulahan Yes, it's mail.Address. I can share my progress so far with. I basically took ABNF from RFCs, made it into Antl4 format and did some changes to tie it together.

**Comment by exander77** [comment]
@jameshoulahan https://github.com/exander77/antlr-rfc/blob/main/RFC.g4

**Comment by exander77** [comment]
@jameshoulahan What these to PRs? I may sound quite forceful, but it will soon be 7 months since I initially reported these issues and since then the number of emails I am not able to import multiplied by 6 times and I had to remove all emails I migrated in April as they are all missing one attachment.

What is the timeline here? We can't have import issues taking years to fix.

**Comment by jameshoulahan** [comment]
We decided to write our own address/date parsers. We aim to have them ready for the upcoming release (address parser is done and undergoing testing and we are starting with the date parser now) and as such don't feel it's worth merging in a fork of net/mail if we never plan to release it to customers.

**Comment by exander77** [comment]
@jameshoulahan Thanks for the info. Hope it goes well, I am willing to beta test and submit PRs into that.

**Comment by jameshoulahan** [comment]
Hi @exander77, i've pushed the address parser code here: https://github.com/jameshoulahan/proton-bridge/tree/feat/correct-address-parsing if you'd like to take a look at it and try it out.

As you can see, I took some of your grammar relaxations (with appropriate credit). But I haven't yet applied all of them; I'm a bit wary of relaxing the grammar too much at first so as to not introduce "false positive" parsing (one of your relaxations, i forget which one now, caused the display-name to wrongly also include the addr-spec, leading to messages with corrupt addresses after import that couldn't be replied to).

**Comment by exander77** [comment]
@jameshoulahan I think what you mean, it was there to handle non-standard cases like these:
```
somebody@somewhere.com somebody@somewhere.com
```
It was not ideal as it would need to be handled in code.

I will try and report back.

**Comment by exander77** [comment]
@jameshoulahan I running it right now. And the first impression is that it is super slow. It may not actually matter much as I am running it with disabled message upload and in reality, it would be blocked by uploading messages to the server. I guess it cat be 100 times slower. I will report back with results, as it takes some time. I would guess that overhead there is building various objects. When I did some hacking with the parser myself. I tried to create minimum objects.

**Comment by exander77** [comment]
Hello @jameshoulahan, I improved error reporting slightly and made a pull in your personal repository.

Except for how slow it is, **this is the best result so far**!

What addresses failed:
```
undisclosed-recipients:
<somebody>
somebody
Somebody somebody@somewhere.com
Somebody :: somebody.com <somebody@somewhere.com>

Matt Barrie, CEO of Freelancer <noreply@updates.freelancer.com>

"GES-ELECTRONICS <GES-ELECTRONICS"@nos.ges.cz,
	a.s. <ges@ges.cz>>
```

The last two cases, I preserved exactly as they appear and I think they should pass, but they fail.

What dates failed:
```
Tuesday 02 March 2010 04:02:33 PM
Wed, 5 Mar 2014 05:27:02 +0100 +0100
Sat, 2 Oct 10 19:59:17 GMT-0700
Wed, 5 May 10 05:59:05 GMT-0700
```

**Comment by jameshoulahan** [comment]
Hi @exander77 , the speed is understandable, I noticed that in the unit tests as well. But I expect it is tiny in comparison to network speeds.

I'm glad you reported back your findings. Many thanks for that. Indeed, I expected some to still fail. As i mentioned above, I didn't relax the grammar as much as you did so as to not lead to wrong parsing results. Depending on customer feedback, I might revisit this. How prevalent are those dates/addresses which still failed?

The address and date parsers have passed QA and will be available in an upcoming release.

**Comment by exander77** [comment]
In my personal emails, the number of occurences is quite low. These errors cover 17 (13 addresses, 4 dates) messages out of 37338, so a 0.045%.

These two are from completely normal services:
```
Matt Barrie, CEO of Freelancer <noreply@updates.freelancer.com>

"GES-ELECTRONICS <GES-ELECTRONICS"@nos.ges.cz,
	a.s. <ges@ges.cz>>
```

First one is parsed without any problems in several tools including standard golang library.

I will try to run the latest version.

**Comment by jameshoulahan** [comment]
It's interesting that the first one, `Matt Barrie, CEO of Freelancer <noreply@updates.freelancer.com>`, is created by a normal service. RFC5322 doesn't permit a comma in the display name. Adding a comma to the allowed characters in the display name grammar breaks other things.

**Comment by exander77** [comment]
> It's interesting that the first one, `Matt Barrie, CEO of Freelancer <noreply@updates.freelancer.com>`, is created by a normal service. RFC5322 doesn't permit a comma in the display name. Adding a comma to the allowed characters in the display name grammar breaks other things.

Yes, I actually have 3 of these emails from Freelancer.com, all have it the same way.
It should be detectable. If there is a `display-name` COMMA `display_name` than it is a single `address`.

**Comment by jameshoulahan** [comment]
Regarding speed, i've run some benchmarks and the new parser is ~5 orders of magnitude slower than the `net/mail` parser... that's pretty extreme. I doubt most users will notice it much as network will be the biggest bottleneck for them, but huge mailboxes (eg 100 000 messages) might spend 30-60mins just parsing message headers alone.

I'm considering using the `net/mail` parser by default and falling back to the antlr-based parser if the `net/mail` one returns an error. But that's only an option if the `net/mail` parser guarantees that no errors implies correctly parsed input. But I wanted to ask, did you notice in your testing any cases where the `net/mail` parser actually parsed an address *wrongly* yet returned no errors? If so, this isn't an option.

**Comment by exander77** [comment]
@jameshoulahan The speed was the first thing I noticed. But I think it would be negligible with networking and when you migrate 100k messages it will be negligible as well. Depending on ProtonMail load it could take a whole half a day to process 100k messages. Even if it added an hour... it already takes so long I usually do this overnight (I did it like 6 times already).

If you want to know about a bottleneck - I think Bridge passes the same message several times. As it can be in INBOX, Important, All Mail and some custom labels. It has no notion that a message can be there several times or it at least seem to me that way. I have like 37k messages and Bridge is processing 100k. If it remembered the Message-ID and just added labels on the server, you can the time in the third.

The other part is really hard to guess when processing thousands of messages. I suggest this... Can you make me a patch that would log address list as a single line so it could be compared as text and logged both `go/imap` and new parser results? I could then split log and compare the results to see what is different. We should do this regardless to see if We didn't break anything.

**Comment by exander77** [comment]
@jameshoulahan Btw, it may be related to golang target being slow: https://github.com/antlr/antlr4/issues/2152
Can Import/Export tool build with profiling options?

**Comment by jameshoulahan** [comment]
> Btw, it may be related to golang target being slow: antlr/antlr4#2152 Can Import/Export tool build with profiling options?

Yes. `make build-ie-nogui` will build a binary in the root directory called `Import-Export`. you'll see by running `./Import-Export --help` that it supports `--mem-prof` and `--cpu-prof` flags. These can be loaded into `go tool pprof` and visualized as you will (i recommend visualizing in the browser, relies on graphviz, there are good entries on the golang blog about how to do this).

> Can you make me a patch that would log address list as a single line so it could be compared as text and logged both go/imap and new parser results?

I assume you mean `net/mail` instead of `go/imap`? Something like this should work fine, adjust as necessary,
```
diff --git a/pkg/message/rfc5322/parser.go b/pkg/message/rfc5322/parser.go
index c4e4c8b..d57066e 100644
--- a/pkg/message/rfc5322/parser.go
+++ b/pkg/message/rfc5322/parser.go
@@ -41,7 +41,23 @@ func ParseAddressList(input string) ([]*mail.Address, error) {

 	antlr.ParseTreeWalkerDefault.Walk(w, p.AddressList())

-	return w.res.([]*mail.Address), w.err
+	parsedAddrList, err := w.res.([]*mail.Address), w.err
+	if err != nil {
+		return nil, err
+	}
+
+	golangAddrList, err := mail.ParseAddressList(input)
+	if err != nil {
+		return nil, err
+	}
+
+	logrus.
+		WithField("pkg/message/rfc5322", parsedAddrList).
+		WithField("net/mail", golangAddrList).
+		WithField("input", input).
+		Warn("Comparing pkg/message/rfc5322 and net/mail parsers")
+
+	return parsedAddrList, nil
 }

 // ParseDateTime parses a valid RFC5322 date-time.
```

**Comment by exander77** [comment]
> I assume you mean net/mail instead of go/imap? Something like this should work fine, adjust as necessary,

You are absolutely correct. I was just working with `go-imap` lately and it completely switched in my brain.

I will try to patch it, profile it and compare results with the new parser and `net/mail` and We will see. Antrl4 is IMHO best currently. I have used Antlr3 as well in the past. Version 4 is well matured, but the golang target seems like a work in progress. I will look into it and we may improve it as well. It is horribly slow, it does not matter for our case much, but still, we may find something to improve there.

**Comment by exander77** [comment]
@jameshoulahan Hello James, first I have a small bug to report if display-name is not quoted and contains dots that dots are replaced by spaces:
```
sombody.somewhere <somebody@somewhere.com>
```
Becomes:
```
```
"somebody somewhere" <somebody@somewere.com>
```

**Comment by exander77** [comment]
> @jameshoulahan Thank's for the info.
> 
> I have run a comparison for `net/mail` (GO), forked and patched `net/mail` (GP) and my Antlr based parser (GA):
> 
> ```
> IN: <>
> GO: [] mail: invalid string
> GP: [<@>] <nil>
> GA: [<@>] <nil>
> 
> IN: Mailer <>
> GO: [] mail: invalid string
> GP: ["Mailer" <@>] <nil>
> GA: ["Mailer" <@>] <nil>
> 
> IN: Somebody Somewhere <somebody@somewhere.com >
> GO: [] mail: unclosed angle-addr
> GP: ["Somebody Somewhere" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Somewhere" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody Somewhere <somebody@somewhere.com. >
> GO: [] mail: trailing dot in atom
> GP: ["Somebody Somewhere" <somebody@somewhere.com.>] <nil>
> GA: ["Somebody Somewhere" <somebody@somewhere.com.>] <nil>
> 
> IN: Somebody Somewhere <somebody@somewhere.com.>
> GO: [] mail: trailing dot in atom
> GP: ["Somebody Somewhere" <somebody@somewhere.com.>] <nil>
> GA: ["Somebody Somewhere" <somebody@somewhere.com.>] <nil>
> 
> IN: Somebody Somewhere <somebody@somewhere.com:25>
> GO: [] mail: unclosed angle-addr
> GP: [] mail: unclosed angle-addr
> GA: ["Somebody Somewhere" <somebody@somewhere.com:25>] <nil>
> 
> IN: Somebody Somewhere <somebody@[10.0.0.1]>
> GO: [] mail: invalid string
> GP: [] mail: invalid string
> GA: ["Somebody Somewhere" <somebody@[10.0.0.1]>] <nil>
> 
> IN: somebody@somewhere <somebody@somewhere.com>
> GO: [] mail: expected comma
> GP: ["somebody@somewhere" <somebody@somewhere.com>] <nil>
> GA: ["somebody somewhere" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody Somewhere < somebody@somewhere.com>
> GO: ["Somebody Somewhere" <somebody@somewhere.com>] <nil>
> GP: ["Somebody Somewhere" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Somewhere" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody :: Somewhere <somebody@somewhere.com>
> GO: [] mail: missing word in phrase: mail: invalid string
> GP: [] mail: missing word in phrase: mail: invalid string
> GA: ["Somebody" <@>] <nil>
> 
> IN: Some Body @ Somewhere <somebody@somewhere.com>
> GO: ["Some Body @ Somewhere" <somebody@somewhere.com>] <nil>
> GP: ["Some Body @ Somewhere" <somebody@somewhere.com>] <nil>
> GA: ["Some Body Somewhere" <somebody@somewhere.com>] <nil>
> 
> IN: somebody
> GO: [] mail: missing '@' or angle-addr
> GP: [] mail: missing '@' or angle-addr
> GA: [<somebody@>] <nil>
> 
> IN: Somebody Somewhere <somebody somewhere>
> GO: [] mail: missing @ in addr-spec
> GP: [] mail: missing @ in addr-spec
> GA: [] mail: 1 syntax errors encountered
> 
> IN: Somebody, Somewhere <somebody@somewhere.com>
> GO: ["Somebody, Somewhere" <somebody@somewhere.com>] <nil>
> GP: ["Somebody, Somewhere" <somebody@somewhere.com>] <nil>
> GA: [<Somebody@> "Somewhere" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody somebody@somewhere.com
> GO: [] mail: no angle-addr
> GP: [] mail: no angle-addr
> GA: ["Somebody" <somebody@somewhere.com>] <nil>
> 
> IN: undisclosed-recipients:
> GO: [] mail: no address
> GP: [] <nil>
> GA: ["undisclosed-recipients" <@>] <nil>
> 
> IN: Somebody Alfa "Beta" <somebody@somewhere.com>
> GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody Alfa Beta <somebody@somewhere.com>
> GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody Alfa"Beta" <somebody@somewhere.com>
> GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody Alfa "Beta"<somebody@somewhere.com>
> GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody "Alfa" "Beta" <somebody@somewhere.com>
> GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody "Alfa""Beta" <somebody@somewhere.com>
> GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody Alfa =?utf-8?Q?Beta?= <somebody@somewhere.com>
> GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody Alfa=?utf-8?Q?Beta?= <somebody@somewhere.com>
> GO: ["Somebody Alfa=?utf-8?Q?Beta?=" <somebody@somewhere.com>] <nil>
> GP: ["Somebody Alfa=?utf-8?Q?Beta?=" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Alfa=?utf-8?Q?Beta?=" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody Alfa =?utf-8?Q?Beta?=<somebody@somewhere.com>
> GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GP: [] mail: no angle-addr
> GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody =?utf-8?Q?Beta?= =?utf-8?Q?Beta?= <somebody@somewhere.com>
> GO: ["Somebody BetaBeta" <somebody@somewhere.com>] <nil>
> GP: ["Somebody BetaBeta" <somebody@somewhere.com>] <nil>
> GA: ["Somebody BetaBeta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody =?utf-8?Q?Beta?==?utf-8?Q?Beta?= <somebody@somewhere.com>
> GO: ["Somebody =?utf-8?Q?Beta?==?utf-8?Q?Beta?=" <somebody@somewhere.com>] <nil>
> GP: ["Somebody BetaBeta" <somebody@somewhere.com>] <nil>
> GA: ["Somebody BetaBeta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody "Alfa"=?utf-8?Q?Beta?= <somebody@somewhere.com>
> GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody "Alfa" =?utf-8?Q?Beta?= <somebody@somewhere.com>
> GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GP: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> 
> IN: Somebody "Alfa" =?utf-8?Q?Beta?=<somebody@somewhere.com>
> GO: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> GP: [] mail: no angle-addr
> GA: ["Somebody Alfa Beta" <somebody@somewhere.com>] <nil>
> ```

Btw, look into these test cases for the behaviour of consecutive encodings.

**Comment by jameshoulahan** [comment]
Hi exander,

thanks for the feedback. It appears net/mail contains some nasty bugs that render it unusable as a "quick, first attempt" parser.

regarding the bugs in the generated parser you've found, thanks!
- periods were replaced with spaces in unquoted display names: yep, my bad, they're part of the obs-phrase and i forgot to account for them; will fix
- comments are display name if they follow angle-addr: interesting... i see in RFC5322 this is just a "note" about legacy implementations... i wouldn't say this is a bug, but i will consider accounting for it
- consecutive quoted strings are joined with space: you're quite right, i see now in RFC2047 it says 
```
   When displaying a particular header field that contains multiple
   'encoded-word's, any 'linear-white-space' that separates a pair of
   adjacent 'encoded-word's is ignored.
```
i missed this -- will fix it!
- wrongly processes empty encoded string: i wouldn't say this is wrong; rfc2047 is explicit in the requirement of *one or more* encoded text chars; the parser is rightly not detecting it as a valid encoded string

**Comment by exander77** [comment]
> * periods were replaced with spaces in unquoted display names: yep, my bad, they're part of the obs-phrase and i forgot to account for them; will fix

Great!

> * comments are display name if they follow angle-addr: interesting... i see in RFC5322 this is just a "note" about legacy implementations... i wouldn't say this is a bug, but i will consider accounting for it

Yes, it is a legacy, for some reason still used.

> * consecutive quoted strings are joined with space: you're quite right, i see now in RFC2047 it says
> 
> ```
>    When displaying a particular header field that contains multiple
>    'encoded-word's, any 'linear-white-space' that separates a pair of
>    adjacent 'encoded-word's is ignored.
> ```
> 
> i missed this -- will fix it!

Great!

> 
> * wrongly processes empty encoded string: i wouldn't say this is wrong; rfc2047 is explicit in the requirement of _one or more_ encoded text chars; the parser is rightly not detecting it as a valid encoded string. I could consider relaxing this requirement though. But why would someone want to send an encoded string of length 0? Better to just not send anything...

I see you are right:
> encoded-text = 1*<Any printable ASCII character other than "?"
>                     or SPACE>

I wonder that myself... but it makes `display-name` into `=?utf-8?q??=` otherwise which is not very nice. This wastes 12 characters for nothing. Probably bad coder implementations which does not account for the string length.

**Comment by exander77** [comment]
Btw, I must say, that otherwise, the parser seems really solid so far. Parses by the book, good error reporting, this may be the best RFC5322 parser yet. You did a hell of a job.

**Comment by jameshoulahan** [comment]
Thanks for the kind words, i'm glad the feedback is positive! 

I've updated my [fork](https://github.com/jameshoulahan/proton-bridge/tree/feat/generated-rfc5322-parser) with the fixes i mentioned above. I won't parse display-name hidden in comments yet as i don't consider that a bug per se. Might tackle it at a later stage though.

One thing i'm not so sure about now -- now that we've relaxed `word` to permit `@`, how should display names containing it be parsed? For example, I have these test cases in `parse_address_list_test.go`, but i'm not that happy with how spaces are added (or not) around `@` in some cases. Thoughts?

```
		{
			input: `first.last <user@domain.com>`,
			addrs: []*mail.Address{
				{
					Name:    `first.last`,
					Address: `user@domain.com`,
				},
			},
		},
		{
			input: `first . last <user@domain.com>`,
			addrs: []*mail.Address{
				{
					Name:    `first.last`,
					Address: `user@domain.com`,
				},
			},
		},
		{
			input: `user@domain <user@domain.com>`,
			addrs: []*mail.Address{{
				Name:    `user@domain`,
				Address: `user@domain.com`,
			}},
		},
		{
			input: `user @ domain <user@domain.com>`,
			addrs: []*mail.Address{
				{
					Name:    `user@domain`,
					Address: `user@domain.com`,
				},
			},
		},
```

**Comment by jameshoulahan** [comment]
Hi @exander77 , i've migrated the rfc5322 parser over to here: https://github.com/ProtonMail/go-rfc5322
i'll close this PR and we can continue the discussion/fixes over there.

**Pull request closed without merging**
