### PR TITLE
[Fuzzing] oss-fuzz support for fuzzing

### PR DESCRIPTION
**Pull request by 0x34d**
Adding [Go Fuzzing](https://go.dev/security/fuzz/) support to identify bugs.
These files can be used in Go-lang [OSS-Fuzz](https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang/) integration.

Running fuzzing locally:
```bash
go test -fuzz=FuzzUnmarshal -parallel=4 $PWD/internal/legacy/credentials
go test -fuzz=FuzzNewParser -parallel=4 $PWD/pkg/message/parser
go test -fuzz=FuzzReadHeaderBody -parallel=4 $PWD/pkg/message
go test -fuzz=FuzzDecodeHeader -parallel=4 $PWD/pkg/mime
go test -fuzz=FuzzDecodeCharset -parallel=4 $PWD/pkg/mime
```

### CODE REVIEW

**Comment by LBeernaertProton** [comment]
@0x34d thank you for your contribution, we will merge this as soon as we are able.

Is there a way for `go test` to automatically run all fuzzing tests rather than having to manual specify each individual test?

**Comment by 0x34d** [comment]
> Is there a way for `go test` to automatically run all fuzzing tests rather than having to manual specify each individual test?

No, there is no such way. 

But I can do something like this in `Makefile`:
```
fuzz:
    @go test -fuzz=FuzzUnmarshal -parallel=4 -fuzztime=1800s $PWD/internal/legacy/credentials
    @go test -fuzz=FuzzNewParser -parallel=4 -fuzztime=1800s $PWD/pkg/message/parser
    @go test -fuzz=FuzzReadHeaderBody -parallel=4 -fuzztime=1800s $PWD/pkg/message
    @go test -fuzz=FuzzDecodeHeader -parallel=4 -fuzztime=1800s $PWD/pkg/mime
    @go test -fuzz=FuzzDecodeCharset -parallel=4 -fuzztime=1800s $PWD/pkg/mime
```

**Comment by 0x34d** [comment]
@LBeernaertProton ping.
Makefile is also updated now, can you merge?

**Comment by LBeernaertProton** [comment]
@0x34d sorry for the silence on this, I have been busy with more pressing matter. I'll try to get this in by end of day tomorrow.

**Comment by LBeernaertProton** [comment]
@0x34d Thanks for your contribution. Your changes have been merged in our internal repository.

**Comment by 0x34d** [comment]
> @0x34d Thanks for your contribution. Your changes have been merged in our internal repository.

Just a question, when will this update be available on the public repository?

**Pull request closed without merging**
