### PR TITLE
Make autostart not show window

### PR DESCRIPTION
**Pull request by kortschak**
This fixes an issue raised via Zendesk (id682815).

### CODE REVIEW

**Comment by kortschak** [comment]
*ping*

**Comment by kortschak** [comment]
*ping*

**Comment by andrzejsza** [comment]
hi @kortschak. we see your point and added this to our backlog (for internal reference - GODT-1133).
Your edit would mean that the window is not shown to all the users who manually open the application and this is not what we want. We'll look into a nicer way of addressing this.

**Comment by kortschak** [comment]
@andrzejsza No, yo're wrong in that; I have been running my local proton-mail bridge with this desktop file; it opens visibly when opened manually and silently when opened on start-up.

**Pull request closed without merging**
