### PR TITLE
Freebsd working

### PR DESCRIPTION
**Pull request by narkoleptik**
I have added in support for building and running on FreeBSD

* Modified the makefile to include support for FreeBSD
* Added a cert_store_freebsd.go file (copied the cert_store_linux.go file)
* Added a pass/pass.go as a local module since the upstream provider (docker) didn't support FreeBSD. 
* Added a function to keychain.go to support the pass.go added module for FreeBSD
* Changed credits.sh to use env to determine location of bash since the original (/bin/bash) is not the location of non-default shells on FreeBSD

### CODE REVIEW

**Comment by ehrlichja** [comment]
Thank you so much for tackling this! It works great for me (tested sending and receiving with the nogui build).

One thing I noticed is that the `sed` in `util/credits.sh` prints errors if it's not GNU sed. Not sure what the best solution is. Maybe try `gsed` and if its not there used `sed`?

**Comment by jameshoulahan** [comment]
Nice! Many thanks for this 😄 Someone will take a look at the changes when we get some time.

**Comment by narkoleptik** [comment]
@cuthix No worries at all 😃 go for it

**Comment by ehrlichja** [comment]
Any movement on this?

**Comment by narkoleptik** [comment]
Changing `sed` to `gsed` clears up the errors with that, but now it isn't compiling due to an error in an included package:

```
go build -tags='' -ldflags '-X github.com/ProtonMail/proton-bridge/internal/constants.Version=2.1.3+git -X github.com/ProtonMail/proton-bridge/internal/constants.Revision=22413e18b4 -X github.com/ProtonMail/proton-bridge/internal/constants.BuildTime=2022-04-16T05:02:27-0400' -o proton-bridge cmd/Desktop-Bridge/main.go
# github.com/ricochet2200/go-disk-usage/du
../../go/pkg/mod/github.com/ricochet2200/go-disk-usage/du@v0.0.0-20210707232629-ac9918953285/diskusage.go:28:24: invalid operation: du.stat.Bavail * uint64(du.stat.Bsize) (mismatched types int64 and uint64)
gmake: *** [Makefile:69: build-nogui] Error 2
```

**Comment by LBeernaertProton** [comment]
Unfortunately, at this point in time, we currently lack the capacity/infrastructure to actively support BSD distributions and to validate that these changes do not cause issues with the current Linux distributions.

**Pull request closed without merging**
