### PR TITLE
Replace "net/mail" with forked version completely

### PR DESCRIPTION
**Pull request by exander77**
This goes above my previous pull request: https://github.com/ProtonMail/proton-bridge/pull/94

But I would like somebody to review it before if it does not break something. But it is a clear drop in. I preserved `mail` name so the change is minimal.

### CODE REVIEW

**Comment by exander77** [comment]
As a next step I would remove hackish attempts done in:
```
e02c7c7 ("Parsing message with empty address as '<>'", 2020-09-24)
ef1671d ("Parsing message with empty CC", 2020-09-24)
4b7c234 ("feat: strip comments from addresses", 2020-09-14)
``
And replace it with a proper fix in forked "net/mail" and over time improve it to be more RFC5322 compliant on one side and more relaxed on the other side.

**Comment by jameshoulahan** [comment]
While I agree there are obvious problems with `net/mail`, I'm not convinced that maintaining a "fork" inside our repository is the best way forward. I'm more inclined to firstly try to upstream the fixes to golang itself.

**Comment by exander77** [comment]
@jameshoulahan I mentioned it earlier somewhere. In a long run, I think `net/mail` should be replaced completely. It's use case is different. Its task is trying to parse an RFC5322 compliant header for dates and addresses. This is not the task you need in Bridge, in Bridge you want to parse each and every address and what you tried to do is stack hacks over it.

There are a few obvious fixes that I try to push there, but the whole design of the library is flawed. It does not support obsoletes and is buggy. The people who wrote were not able to follow RFCs. It is a mixed lexer/parser and very hard to maintain in my opinion.

Think not about it as a fork, but as a starting point for your own code.

In my opinion the best way how to approach this would be to generate lexer/parser through some compiler generator and tie i together to be drop in replacement for whole `net/mail`.

**Comment by jameshoulahan** [comment]
> In my opinion, the best way how to approach this would be to generate lexer/parser through some lexer/parser generator and tie I together to be a drop-in replacement for the whole net/mail.

Totally agree. I started playing around last night generating an address parser using ANTLR given the formal grammar specified in RFC5322. I've done this before for IMAP and it worked splendidly, and addresses are a much simpler problem than IMAP, so I'm quite confident I could do it well. But that's quite a big undertaking and there are parts of net/mail that work quite well. And also, parsers generated from a grammar usually cannot easily recover from errors or nonstandard input... they either parse it or they fail completely.

**Comment by exander77** [comment]
@jameshoulahan Yes, this is the way forward for sure. For the meantime, I think using this forked version would be extremely beneficial. I would mention that your regexp for removing comments is actually breaking correct addresses. I write it outside of parser is nearly impossible as you need to account for escaping, quoting, encoding etc.

Supplied version works much better.

**Comment by exander77** [comment]
@jameshoulahan I found one of your other hacks over the standard go library. You parse whole media type, decode it, make it a string again and reparse it with the standard library. Is this supposed to be better than forking the code? Firstly I worry it is introducing some errors - as I am not sure you can generally do it and it copies the code from the library anyway.

```
// changeEncodingAndKeepLastParamDefinition is necessary to modify behaviour
// provided by the golang standard libraries.
func changeEncodingAndKeepLastParamDefinition(v string) (out string, err error) {
	log := logrus.WithField("pkg", "pm-mime")

	out = v // By default don't do anything with that.
	keepOrig := true

	i := strings.Index(v, ";")
	if i == -1 {
		i = len(v)
	}
	mediatype := strings.TrimSpace(strings.ToLower(v[0:i]))

	params := map[string]string{}
	var continuation map[string]map[string]string

	v = v[i:]
	for len(v) > 0 {
		v = strings.TrimLeftFunc(v, unicode.IsSpace)
		if len(v) == 0 {
			break
		}
		key, value, rest := consumeMediaParam(v)
		if key == "" {
			break
		}

		pmap := params
		if idx := strings.Index(key, "*"); idx != -1 {
			baseName := key[:idx]
			if continuation == nil {
				continuation = make(map[string]map[string]string)
			}
			var ok bool
			if pmap, ok = continuation[baseName]; !ok {
				continuation[baseName] = make(map[string]string)
				pmap = continuation[baseName]
			}
			if isFirstContinuation(key) {
				charset, _, err := get2231Charset(value)
				if err != nil {
					log.Errorln("Filter params:", err)
					v = rest
					continue
				}
				if charset != "utf-8" && charset != "us-ascii" {
					keepOrig = false
				}
			}
		}
		if _, exists := pmap[key]; exists {
			keepOrig = false
		}
		pmap[key] = value
		v = rest
	}

	if keepOrig {
		return
	}

	for paramKey, contMap := range continuation {
		value, err := mergeContinuations(paramKey, contMap)
		if err == nil {
			params[paramKey+"*"] = value
			continue
		}

		// Fallback.
		log.Errorln("Merge param", paramKey, ":", err)
		for ck, cv := range contMap {
			params[ck] = cv
		}
	}

	// Merge ;
	out = mediatype
	for k, v := range params {
		out += ";"
		out += k
		out += "="
		out += v
	}

	return
}
```

**Comment by exander77** [comment]
@jameshoulahan Great news, thank you! I am trying to investigate what is causing `mime: invalid media parameter` error currently. It may be related to this hack or to a nonstandard encoding or the fact that filename is encoded by word encoding and not the special encoding scheme in RFC2231.

If my pull requests could be review and possibly improved (as I am not familiar with the codebase yet) and merged, it would be great. I am also not a Golang programmer, this is my first time working with Golang, but it is similar to other languages I used and I tried to follow the conventions of the project.

Having custom parser generated for RFC5322 is the best option for the long term. But I think for the immediate benefit of the users, this is not bad.

There is one troubling part here: https://github.com/ProtonMail/proton-bridge/pull/103/commits/4ba14aeb395fdb7cae2c4e601a77072355efe31d

I have duplicated contents of `ConvertToUTF8` and `selectSuitableDecoder` and modified them for my needs, this may be handled in some better way, but I didn't want to mess with the original function to break something, so `ConvertHeaderToUTF8` and `selectSuitableHeaderDecoder` are completely separate.

**Comment by jameshoulahan** [comment]
https://github.com/ProtonMail/proton-bridge/pull/94#issuecomment-723961724

**Comment by exander77** [comment]
@jameshoulahan Regarding `invalid media parameter`: https://www.reddit.com/r/ProtonMail/comments/jqx3vh/error_importing_emails_with_attachments/

We should do something about it. I may affect some users in a very negative way. I think it relates to the encoding of the filename. But I have only a few samples.

**Comment by jameshoulahan** [comment]
Agreed. This issue is also on our backlog of things to look into. Unfortunately, that backlog is quite large.

Now that address/date parsing is improved, we should be more successful in parsing headers. After parsing headers, the next step is collecting attachments. Users who previously had issues parsing headers will now succeed there and advance to collecting attachments. As such, the upcoming releases should give us a better insight into how prevalent this `invalid media parameter` issue really is and help determine priorities.

**Pull request closed without merging**
