### PR TITLE
Singificantly improve Date parsing and Address parsing

### PR DESCRIPTION
**Pull request by exander77**
Forked `net/mail` from go master and added it to proton-bridge repository.
Replaced ParseDate with forked implementation.
Fixed `T` timezone bug as per suggestion: https://github.com/golang/go/issues/39260.
Modified it by reordering layout generation (most common case is generated first now). This alone should speed it up by order of magnitude. Original generation was quite retarded as uncommon layouts were generated first. Wtf were they thinking?
Added empty zone `""` and `"GMT-0700"` zone format for relaxation. The empty zone should fallback to `+0000` by `time.Parse`.
Worse case is now checking against `2*2*2*2*4` = 64 layouts instead of original 32 but the case is extremely rare. The average case is now in checking against 1 layout instead of 16+.

The original order is:
```
2 Jan 2006 15:04:05 -0700
2 Jan 2006 15:04:05 MST
2 Jan 2006 15:04 -0700
2 Jan 2006 15:04 MST
2 Jan 06 15:04:05 -0700
2 Jan 06 15:04:05 MST
2 Jan 06 15:04 -0700
2 Jan 06 15:04 MST
02 Jan 2006 15:04:05 -0700
02 Jan 2006 15:04:05 MST
02 Jan 2006 15:04 -0700
02 Jan 2006 15:04 MST
02 Jan 06 15:04:05 -0700
02 Jan 06 15:04:05 MST
02 Jan 06 15:04 -0700
02 Jan 06 15:04 MST
Mon, 2 Jan 2006 15:04:05 -0700
Mon, 2 Jan 2006 15:04:05 MST
Mon, 2 Jan 2006 15:04 -0700
Mon, 2 Jan 2006 15:04 MST
Mon, 2 Jan 06 15:04:05 -0700
Mon, 2 Jan 06 15:04:05 MST
Mon, 2 Jan 06 15:04 -0700
Mon, 2 Jan 06 15:04 MST
Mon, 02 Jan 2006 15:04:05 -0700
Mon, 02 Jan 2006 15:04:05 MST
Mon, 02 Jan 2006 15:04 -0700
Mon, 02 Jan 2006 15:04 MST
Mon, 02 Jan 06 15:04:05 -0700
Mon, 02 Jan 06 15:04:05 MST
Mon, 02 Jan 06 15:04 -0700
Mon, 02 Jan 06 15:04 MST
```
The new order is:
```
Mon, 2 Jan 2006 15:04:05 -0700
Mon, 02 Jan 2006 15:04:05 -0700
Mon, 2 Jan 06 15:04:05 -0700
Mon, 02 Jan 06 15:04:05 -0700
Mon, 2 Jan 2006 15:04:05 MST
Mon, 02 Jan 2006 15:04:05 MST
Mon, 2 Jan 06 15:04:05 MST
Mon, 02 Jan 06 15:04:05 MST
Mon, 2 Jan 2006 15:04:05 
Mon, 02 Jan 2006 15:04:05 
Mon, 2 Jan 06 15:04:05 
Mon, 02 Jan 06 15:04:05 
Mon, 2 Jan 2006 15:04:05 GMT-0700
Mon, 02 Jan 2006 15:04:05 GMT-0700
Mon, 2 Jan 06 15:04:05 GMT-0700
Mon, 02 Jan 06 15:04:05 GMT-0700
Mon, 2 Jan 2006 15:04 -0700
Mon, 02 Jan 2006 15:04 -0700
Mon, 2 Jan 06 15:04 -0700
Mon, 02 Jan 06 15:04 -0700
Mon, 2 Jan 2006 15:04 MST
Mon, 02 Jan 2006 15:04 MST
Mon, 2 Jan 06 15:04 MST
Mon, 02 Jan 06 15:04 MST
Mon, 2 Jan 2006 15:04 
Mon, 02 Jan 2006 15:04 
Mon, 2 Jan 06 15:04 
Mon, 02 Jan 06 15:04 
Mon, 2 Jan 2006 15:04 GMT-0700
Mon, 02 Jan 2006 15:04 GMT-0700
Mon, 2 Jan 06 15:04 GMT-0700
Mon, 02 Jan 06 15:04 GMT-0700
2 Jan 2006 15:04:05 -0700
02 Jan 2006 15:04:05 -0700
2 Jan 06 15:04:05 -0700
02 Jan 06 15:04:05 -0700
2 Jan 2006 15:04:05 MST
02 Jan 2006 15:04:05 MST
2 Jan 06 15:04:05 MST
02 Jan 06 15:04:05 MST
2 Jan 2006 15:04:05 
02 Jan 2006 15:04:05 
2 Jan 06 15:04:05 
02 Jan 06 15:04:05 
2 Jan 2006 15:04:05 GMT-0700
02 Jan 2006 15:04:05 GMT-0700
2 Jan 06 15:04:05 GMT-0700
02 Jan 06 15:04:05 GMT-0700
2 Jan 2006 15:04 -0700
02 Jan 2006 15:04 -0700
2 Jan 06 15:04 -0700
02 Jan 06 15:04 -0700
2 Jan 2006 15:04 MST
02 Jan 2006 15:04 MST
2 Jan 06 15:04 MST
02 Jan 06 15:04 MST
2 Jan 2006 15:04 
02 Jan 2006 15:04 
2 Jan 06 15:04 
02 Jan 06 15:04 
2 Jan 2006 15:04 GMT-0700
02 Jan 2006 15:04 GMT-0700
2 Jan 06 15:04 GMT-0700
02 Jan 06 15:04 GMT-0700
```

### CODE REVIEW

**Comment by exander77** [comment]
There is a lot of weird shit in address parsing as well.
Headers were firstly decoded in `emersion/go-message` as `Text()` called in `forEachDecodedHeaderField` as it decodes the header, then by `pmmime.DecodeHeader ` if that failed and then mail.parseAddressList would try to do the same thing if it was needed. Each one with its own `WordDecoder`. I cut the decoding out and replaced it with the passing of the appropriate `WordDecoder` into `AddressParser.ParseList` and use this and this only.

**Comment by jameshoulahan** [comment]
I've taken a brief look at your change to address parsing (will look at date-related changes when I find some more time).

I agree in general with the changes. Thanks! Though I think it's important that we use a word decoder in `parseAddressList(...)` (in `pkg/message/header.go`) that understands all the extra charsets we've added support for.

I believe you already noticed this yourself, hence the TODO comment as follows
```
	// TODO: reuse?
	var addressParser = &mail.AddressParser{WordDecoder: pmmime.GetWordDecoder()}

	addrs, err = addressParser.ParseList(parseAddressComment(val))
```

I think we should indeed reuse the address parser rather than call `mail.ParseAddressList(...)` as it will have support for more charsets than the default one thanks to our custom word decoder in `pkg/mime`.

**Comment by exander77** [comment]
> I've taken a brief look at your change to address parsing (will look at date-related changes when I find some more time).
> 
> I agree in general with the changes. Thanks! Though I think it's important that we use a word decoder in `parseAddressList(...)` (in `pkg/message/header.go`) that understands all the extra charsets we've added support for.

Yes, this is actually done by passing `WordDecoder` to the `mail.AddressParse` construction which replaces `mail.parseAddressList` call, I have added `GetWordDecoder` to `pmmime`. It is important to use this decoder (which supports more charsets) everywhere. I would create a single `mail.AddressParser` in `pkg/message/header.go`.

The reuse comment was more about, creating only a single `mail.AddressParse` object. I will make a pull with that as well.

**Comment by exander77** [comment]
@jameshoulahan I added AddressParser reuse to this pull.

**Comment by jameshoulahan** [comment]
Hi @exander77, the new rfc5322 parser has just made it into `master` of this repo. As such, i'll be closing these PRs of yours. Many thanks for your assistance in helping to develop it! Without your thorough testing and feedback, we wouldn't have gotten as far as we did.

**Comment by exander77** [comment]
@jameshoulahan Great news!

**Comment by exander77** [comment]
@jameshoulahan I may clear my opened issues myself after trying master and see what we have left to solve.

**Pull request closed without merging**
